export  const Action_Types = {
    ADD_JOB : "ADD_JOB",
    FILTER_JOBS_BYTIME : "FILTER_JOBS_BYTIME",
    FILTER_JOBS_BYCITY : "FILTER_JOBS_BYCITY",
    FILTER_JOBS_BYSEARCH : "FILTER_JOBS_BYSEARCH",
    ADD_USER: "ADD_USER",
    ADD_NEW_EMPLOYEE : "ADD_NEW_EMPLOYEE",
    REMOVE_FROM_EMPLOYEES : "REMOVE_FROM_EMPLOYEES",
    LOGOUT : "LOGOUT"
}